export const SANPHAM_REQUESTED = "SANPHAM_REQUESTED";
export const SANPHAM_SUCCEED = "SANPHAM_SUCCEED";
export const SANPHAM_FAILED = "SANPHAM_FAILED";

export const CTSANPHAM_REQUESTED = "CTSANPHAM_REQUESTED";
export const CTSANPHAM_SUCCEED = "CTSANPHAM_SUCCEED";
export const CTSANPHAM_FAILED = "CTSANPHAM_FAILED";

export const CATEGORY_REQUESTED = "CATEGORY_REQUESTED";
export const CATEGORY_SUCCEED = "CATEGORY_SUCCEED";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

export const SP_CATEGORY_REQUESTED = "SP_CATEGORY_REQUESTED";
export const SP_CATEGORY_SUCCEED = "SP_CATEGORY_SUCCEED";
export const SP_CATEGORY_FAILED = "SP_CATEGORY_FAILED";

export const BRAND_REQUESTED = "BRAND_REQUESTED";
export const BRAND_SUCCEED = "BRAND_SUCCEED";
export const BRAND_FAILED = "BRAND_FAILED";

export const SP_BRAND_REQUESTED = "SP_BRAND_REQUESTED";
export const SP_BRAND_SUCCEED = "SP_BRAND_SUCCEED";
export const SP_BRAND_FAILED = "SP_BRAND_FAILED";

export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCEED = "REGISTER_SUCCEED";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const CHECK_LOGIN = "CHECK_LOGIN";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCEED = "LOGOUT_SUCCEED";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const PERSONAL_REQUESTED = "PERSONAL_REQUESTED";
export const PERSONAL_SUCCEED = "PERSONAL_SUCCEED";
export const PERSONAL_FAILED = "PERSONAL_FAILED";

export const CART_REQUESTED = "CART_REQUESTED";
export const CART_SUCCEED = "CART_SUCCEED";
export const CART_FAILED = "CART_FAILED";

export const ADDCART_REQUESTED = "ADDCART_REQUESTED";
export const ADDCART_SUCCEED = "ADDCART_SUCCEED";
export const ADDCART_FAILED = "ADDCART_FAILED";

export const DELETECART_REQUESTED = "DELETECART_REQUESTED";
export const DELETECART_SUCCEED = "DELETECART_SUCCEED";
export const DELETECART_FAILED = "DELETECART_FAILED";

export const DELETEALLCART_REQUESTED = "DELETEALLCART_REQUESTED";
export const DELETEALLCART_SUCCEED = "DELETEALLCART_SUCCEED";
export const DELETEALLCART_FAILED = "DELETEALLCART_FAILED";

export const BILL_REQUESTED = "BILL_REQUESTED";
export const BILL_SUCCEED = "BILL_SUCCEED";
export const BILL_FAILED = "BILL_FAILED";

export const BILL_RESETED = "BILL_RESETED";
